name = "movie-app-backend"
compatibility_date = "2023-10-01"
main = "worker.js"

[[kv_namespaces]]
binding = "MOVIE_APP"
id = "ae9e7aa818cd45c08e8538140f60d1af"
preview_id = "7b6c3f0df5e0455a9b7f3028354d83e0"