name = "movie-app-backend"
compatibility_date = "2023-10-01"
main = "worker.js"

[[d1_databases]]
binding = "DB"
database_name = "movie-app-db"
database_id = "93cfcbcb-6e39-4f40-92d4-b7b7c4048fae"

[vars]
JWT_SECRET = "your-jwt-secret-key-here-change-in-production"