name = "movie-app-backend"
compatibility_date = "2024-09-23"
main = "src/index.js"

[[d1_databases]]
binding = "DB"
database_name = "movie-app-db"
database_id = "b992ffa5-0a23-49c1-9840-0e523799bdde"

[vars]
JWT_SECRET = "default-secret-change-in-production"
TMDB_API_KEY = "e723914bacd3f287ba6464803d8f41ce"